yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='index')),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор')
    text = models.TextField(
        verbose_name='Коментарий')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Создан')
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Обнавлен')
    active = models.BooleanField(
        default=True,
        verbose_name='Активен')

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Коментарии'
        verbose_name = 'Коментарий'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор')

    class Meta:
        verbose_name_plural = 'Подписчика'
        verbose_name = 'Подписчик'

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': ('Текст поста'), 'group': ('Группа')}
        help_texts = {'text': ('Текст нового поста'),
                      'group': ('Группа, к которой будет относиться пост')}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': ('Коментарий')}
        help_texts = {'text': ('Текст нового коментария')}

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Group, Post, Follow, User
from .constants import POSTS_PER_PAGE
from .utils import get_page_context


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.order_by('-pub_date')
    page_obj = get_page_context(request, posts, count_post=POSTS_PER_PAGE)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


@cache_page(20)
def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    page_obj = get_page_context(request, post_list, count_post=POSTS_PER_PAGE)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.order_by('-pub_date')
    posts_count = Post.objects.filter(author=author).count()
    page_obj = get_page_context(request, posts, count_post=POSTS_PER_PAGE)
    following = request.user.is_authenticated
    if following:
        following = author.following.filter(user=request.user).exists()
    context = {
        'author': author,
        'posts': posts,
        'posts_count': posts_count,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'requser': request.user,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        create_post = form.save(commit=False)
        create_post.author = request.user
        create_post.save()
        return redirect('posts:profile', create_post.author)
    context = {'form': form}
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form, 'post': post, 'is_edit': True}
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    page_obj = get_page_context(request, posts, count_post=POSTS_PER_PAGE)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    follow = get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    )
    follow.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}{% endblock %}
{% block content %}
<div class="row justify-content-center">
<div class="col-md-8 p-5">
  <div class="card">
    <div class="card-header">{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}</div>
    <div class="card-body">
        {% load user_filters %}
        {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
        {% endif %}
        <form method="post" 
          {% if is_edit %} 
              action="{% url 'posts:post_edit' post.id %}" 
          {% else %}
              action="{% url 'posts:post_create' %}" 
          {% endif %}} enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}<div class="form-group row my-3"
            {% if field.field.required %} 
              aria-required="true"
            {% else %}
              aria-required="false"
            {% endif %}
          >
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
            </label>
            <div>
            {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          </div>
        {% endfor %}
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">{% if is_edit %}Сохранить{% else %}Добавить{% endif %}</button>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Подписки{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% for post in page %}

    <ul class="list-group">
    <li class="list-group-item list-group-item-light">
      Автор: <a href="{% url 'posts:profile' post.author %}">
        {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
      </a>
    </li>
    <li class="list-group-item list-group-item-light">
      Дата публикации: <strong>{{ post.pub_date|date:'d E Y' }}</strong>
    </li>
    </ul>

<div class="card bg-light" style="width: 100%">
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img-top" src="{{ im.url }}">
  {% endthumbnail %}
  <div class="card-body">
    <h4 class="card-title">Заголовок</h4>
    <p class="card-text">
      {{ post.text|linebreaksbr }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Подробная информация</a>  
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-primary">Все записи группы "{{ post.group }}"</a>
    {% endif %}
  </div>
</div>

{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
    {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
  {% block title %}
    {{title}}
      Записи сообщества {{group.title}}
  {% endblock %}
  {% block content %}
    <div class="container py-5">
      <h1>{{group.title}}</h1>
      <p>{{group.description|linebreaks }}</p>
      {% for post in posts %}
      <article>
        <ul>
          <li>Автор: {{ post.author.get_full_name }}</li>
          <li>Дата публикации: {{ post.pub_date|date:'d E Y' }}</li>
        </ul>
        <div class="card bg-light" style="width: 100%">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img-top" src="{{ im.url }}">
          {% endthumbnail %}
          <div class="card-body">
            <h4 class="card-title">Заголовок</h4>
        <p>{{ post.text|linebreaks }}</p>
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
      </article>
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' with index=True %}
  <div class="container py-5">
    <h1>{{ title }}</h1>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>Автор: {{ post.author.get_full_name }}</li>
          <li>Дата публикации: {{ post.pub_date|date:'d E Y' }}</li>
        </ul>
        <div class="card bg-light" style="width: 100%">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img-top" src="{{ im.url }}">
          {% endthumbnail %}
          <div class="card-body">
            <h4 class="card-title">Заголовок</h4>
            
        <p>{{ post.text }}</p>
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}
        <hr> {% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </article>    
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Пост {{ post|truncatechars:30 }}{% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:'d E Y' }}
      </li>
        {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group }}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        </li>
        {% endif %}
      <li class="list-group-item">
        Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
      </li>
      <li class="list-group-item">
        Всего постов автора: {{ post.author.posts.count }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">

<div class="card bg-light" style="width: 100%">
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img-top" src="{{ im.url }}">
  {% endthumbnail %}
  <div class="card-body">
    <h4 class="card-title">Заголовок</h4>
    <p class="card-text">
      {{ post.text|linebreaksbr }}
    </p>
    {% if post.author == requser %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
        Редактировать запись
      </a>
    {% endif %}
  </div>
</div>
    {% load user_filters %}
    {% if comments.count != 0 %}
    {% with comments.count as total_comments %}
    <hr>
    <figure>
      <blockquote class="blockquote">
        <div class="shadow-sm p-2 bg-white rounded">
          Комментариев {{ total_comments }}
        </div>
      </blockquote>
    </figure>
    {% endwith %}
    {% endif %}

    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить комментарий</button>
            </form>
          </div>
      </div>
    {% endif %}

    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <div class="alert alert-primary" role="alert">
            {{ comment.created|date:'d E Y' }} <a href="{% url 'posts:profile' comment.author.username %}">{{ comment.author.get_full_name }}</a>:
          </div>
          <figure>
            <blockquote class="blockquote">
              <div class="shadow-sm p-3 bg-white">
                {{ comment.text|linebreaks }}
              </div>
            </blockquote>
          </figure>
        </div>
      </div>

    {% empty %}
    <hr>
    <figure>
      <blockquote class="blockquote">
        <div class="shadow-sm p-2 bg-white rounded">
          Комментариев нет, будь первым! 
        </div>
      </blockquote>
    </figure>
    {% endfor %}

</article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Автор {{post.author.get_full_name}}{% endblock %}
{% block content %}
      
<div class="card bg-light" style="width: 100%">
  <div class="card-body">
      <h1 class="card-title">Все посты пользователя {% if author.get_full_name %}{{ author.get_full_name }}{% else %}{{ author }}{% endif %}</h1>
      <h3 class="card-text">Всего постов: {{ page_obj.paginator.count }}</h3>
      {% if request.user != author %}
          {% if following %}
              <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
              >
              Отписаться
              </a>
              {% else %}
              <a
                  class="btn btn-lg btn-primary"
                  href="{% url 'posts:profile_follow' author.username %}" role="button"
              >
              Подписаться
              </a>
          {% endif %}
      {% endif %}
  </div>
</div>
        {%for post in page_obj %}   
        <article>
          <ul>
            <li>
              Автор: {{post.author.get_full_name}}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{post.pub_date|date:"d E Y"}} 
            </li>
          </ul>
          <div class="card bg-light" style="width: 100%">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img-top" src="{{ im.url }}">
            {% endthumbnail %}
            <div class="card-body">
              <h4 class="card-title">Заголовок</h4>
              
          <p>
          {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>
        {% if post.group %}       
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>        
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
{% endblock %}